name: Alexanderbierling
favicon: null
layout_spectrum: 0.14107053587213159
typography_spectrum: 0.4805895290337503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8161865447182208
  lightness: 0.8101573989260942
  saturation: 0.2316827061586082
  rhythmicContrast: 0.30861992412246764
purpose: []
